repos:
  - repo: https://github.com/Kevino135/skripsi
    rev: 0.1.9.3
    hooks:
      - id: gitSanity
        stages: [commit]
      - id: gitSanityPull
        always_run: true
        stages: [post-merge]
      - id: gitSanityPush
        stages: [push]